import type {
  CertificationData,
  EducationData,
  ProfileData,
  ProjectData,
  SkillData,
  SocialLinkData,
} from "@/types";

export const fallbackProfile: ProfileData = {
  id: 1,
  name: "Tanvir Rahman",
  brandText: "Tanvir Rahman",
  title: "AI Engineer",
  typingLines: [
    "I build machine learning models",
    "I create intelligent applications",
    "I turn data into useful products",
  ],
  bio: "AI Engineer focused on building intelligent systems that solve real problems. I work across machine learning, backend development, and production-ready AI applications.",
  avatarUrl: "",
  heroBadgeText: "ai · ml · systems",
  resumeUrl: "",
  cvUrl: "",
  email: "tanvirrahmanaz@gmail.com",
  githubUsername: "tanvirrahmanaz",
  location: "Dhaka, Bangladesh",
};

export const fallbackSocialLinks: SocialLinkData[] = [
  {
    id: "fallback-github",
    platform: "github",
    label: "GitHub",
    url: "https://github.com/tanvirrahmanaz",
    order: 0,
  },
  {
    id: "fallback-linkedin",
    platform: "linkedin",
    label: "LinkedIn",
    url: "https://linkedin.com/in/tanvirrahmanaz",
    order: 1,
  },
];

export const fallbackSkills: SkillData[] = [
  { id: "python", name: "Python", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg", category: "Languages", order: 0 },
  { id: "scikit-learn", name: "scikit-learn", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/scikitlearn/scikitlearn-original.svg", category: "ML / AI", order: 1 },
  { id: "pandas", name: "Pandas", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg", category: "ML / AI", order: 2 },
  { id: "tensorflow", name: "TensorFlow", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg", category: "ML / AI", order: 3 },
  { id: "pytorch", name: "PyTorch", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg", category: "ML / AI", order: 4 },
  { id: "javascript", name: "JavaScript", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg", category: "Languages", order: 5 },
  { id: "nextjs", name: "Next.js", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg", category: "Web", order: 6 },
  { id: "postgresql", name: "PostgreSQL", logoUrl: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg", category: "Tools", order: 7 },
];

const fallbackDate = "2026-08-07T00:00:00.000Z";

export const fallbackProjects: ProjectData[] = [
  {
    id: "fallback-sms-spam-classifier",
    title: "SMS Spam Classifier",
    slug: "sms-spam-classifier",
    summary: "An NLP web application that classifies text messages as spam or legitimate using a trained machine-learning model.",
    content: "## Overview\n\nA practical machine-learning application for detecting spam messages from user-provided text.\n\n## Highlights\n\n- NLP preprocessing\n- Spam-versus-ham classification\n- Streamlit prediction interface\n- Public live deployment",
    imageUrl: "https://opengraph.githubassets.com/1/tanvirrahmanaz/SMS-Spam-Classifier-Model",
    liveUrl: "https://sms-spam-classifier-model.onrender.com/",
    githubUrl: "https://github.com/tanvirrahmanaz/SMS-Spam-Classifier-Model",
    techStack: ["Python", "scikit-learn", "NLTK", "Streamlit"],
    featured: true,
    order: 0,
    createdAt: fallbackDate,
    updatedAt: fallbackDate,
  },
  {
    id: "fallback-topic-modeling",
    title: "Topic Modeling",
    slug: "topic-modeling",
    summary: "An NLP project that explores hidden themes and patterns inside collections of text.",
    content: "## Overview\n\nA notebook-based NLP project focused on topic discovery and exploratory analysis of textual datasets.\n\n## Highlights\n\n- Text preprocessing\n- Topic discovery experiments\n- Exploratory NLP analysis\n- Reproducible notebook workflow",
    imageUrl: "https://opengraph.githubassets.com/1/tanvirrahmanaz/Topic_modeling",
    liveUrl: "",
    githubUrl: "https://github.com/tanvirrahmanaz/Topic_modeling",
    techStack: ["Python", "NLP", "Topic Modeling", "Jupyter"],
    featured: true,
    order: 1,
    createdAt: fallbackDate,
    updatedAt: fallbackDate,
  },
  {
    id: "fallback-ml-projects",
    title: "Machine Learning Project Collection",
    slug: "machine-learning-project-collection",
    summary: "A collection of machine-learning notebooks covering data preparation, model training, and evaluation.",
    content: "## Overview\n\nA growing collection of practical machine-learning work.\n\n## Highlights\n\n- Data cleaning and exploratory analysis\n- Feature preparation\n- Model-training experiments\n- Evaluation workflows",
    imageUrl: "https://opengraph.githubassets.com/1/tanvirrahmanaz/ML_project",
    liveUrl: "",
    githubUrl: "https://github.com/tanvirrahmanaz/ML_project",
    techStack: ["Python", "scikit-learn", "Pandas", "Jupyter"],
    featured: true,
    order: 2,
    createdAt: fallbackDate,
    updatedAt: fallbackDate,
  },
  {
    id: "fallback-deep-learning",
    title: "Deep Learning Lab",
    slug: "deep-learning-lab",
    summary: "Hands-on deep-learning experiments focused on neural networks and model-training workflows.",
    content: "## Overview\n\nA learning-focused repository containing deep-learning experiments and notebooks.\n\n## Highlights\n\n- Neural-network experimentation\n- Model-training practice\n- Notebook-based workflow\n- Ongoing deep-learning study",
    imageUrl: "https://opengraph.githubassets.com/1/tanvirrahmanaz/Deep-Learning",
    liveUrl: "",
    githubUrl: "https://github.com/tanvirrahmanaz/Deep-Learning",
    techStack: ["Python", "Deep Learning", "Neural Networks", "Jupyter"],
    featured: true,
    order: 3,
    createdAt: fallbackDate,
    updatedAt: fallbackDate,
  },
  {
    id: "fallback-room-mate-finder",
    title: "Room Mate Finder",
    slug: "room-mate-finder",
    summary: "A full-stack platform for publishing room listings and connecting with potential roommates.",
    content: "## Overview\n\nA responsive full-stack roommate-finding platform.\n\n## Highlights\n\n- Authentication and protected APIs\n- Room-listing CRUD\n- Search, sorting, and filtering\n- React client and Express API",
    imageUrl: "https://opengraph.githubassets.com/1/tanvirrahmanaz/room-mate-finder-client",
    liveUrl: "https://room-mate-finderbd.web.app/",
    githubUrl: "https://github.com/tanvirrahmanaz/room-mate-finder-client",
    techStack: ["React", "Tailwind CSS", "Express", "MongoDB"],
    featured: true,
    order: 4,
    createdAt: fallbackDate,
    updatedAt: fallbackDate,
  },
  {
    id: "fallback-courseflow",
    title: "CourseFlow",
    slug: "courseflow",
    summary: "A full-stack course-management platform for students and instructors.",
    content: "## Overview\n\nStudents can discover and enroll in courses while instructors manage their own courses through a protected dashboard.\n\n## Highlights\n\n- Firebase authentication\n- Protected backend endpoints\n- Enrollment and seat management\n- Instructor-owned course CRUD",
    imageUrl: "https://opengraph.githubassets.com/1/tanvirrahmanaz/course-management",
    liveUrl: "https://course-management-bd.web.app/",
    githubUrl: "https://github.com/tanvirrahmanaz/course-management",
    techStack: ["React", "Firebase", "Express", "MongoDB"],
    featured: true,
    order: 5,
    createdAt: fallbackDate,
    updatedAt: fallbackDate,
  },
];

export const fallbackEducation: EducationData[] = [];
export const fallbackCertifications: CertificationData[] = [];
